<a href="https://colab.research.google.com/github/Akash-12-web/Samsung-Inovation-AIML/blob/main/SIC_ML_Coding_Exercises/SIC_ML_Chapter_03_Coding_Exercises/ex_0201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Coding Exercise 0201

### 1. NumPy library:

#### 1.1. NumPy basics:

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[1 3 5 7 9]


In [4]:
lst = [1, 2, "a", False]

In [5]:
type(lst[3])

bool

In [6]:
lstToArr = np.array(lst)    #Convert everything to the highest value
print(lstToArr)

['1' '2' 'a' 'False']


In [7]:
arr3 = arr1

In [8]:
id(arr1)

133902374512816

In [9]:
id(arr3)

133902374512816

In [10]:
arr4 = arr1.copy()

In [11]:
id(arr4)

133902374504560

In [12]:
arr5 = np.array([1, 2, 3], dtype = float)
print(arr5)

[1. 2. 3.]


In [13]:
print(type(arr1))
print(type(arr2))
print(type(arr5))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


#### 1.2. Creating NumPy arrays:

numpy.arange() function:

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print(np.arange(10,20))

[10 11 12 13 14 15 16 17 18 19]


In [16]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [17]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
len(arr)

10

In [19]:
"""
size gives you the total number of elements in the array.
size can also query the sizes of specific axes with np.size.
len gives the length of the first dimension.
"""
print(arr.size)

10


numpy.linspace() function:

In [20]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
arr = np.linspace(0, 10, 5, retstep=True)
print(type(arr))
print(arr)
# print(arr.size)     # Since it is not a numpy array, it gives error (size is attribute of numpy array)


<class 'tuple'>
(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))


In [22]:
print(arr)
type(arr[0])

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))


numpy.ndarray

In [23]:
arr[1]

np.float64(2.5)

numpy.zeros() and numpy.ones() functions:

In [24]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros(5, dtype ='int64')

array([0, 0, 0, 0, 0])

In [27]:
np.zeros(5, dtype ='int64').dtype

dtype('int64')

In [28]:
arr = np.ones((2,3), dtype ='int_')
print(arr)

[[1 1 1]
 [1 1 1]]


In [29]:
arr.size

6

In [30]:
len(arr)

2

In [31]:
arr.dtype

dtype('int64')

In [32]:
arr.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [33]:
print(arr.astype('float32'), "\n")
print(arr, "\n")
print(arr.astype('float32').size, "\n")

[[1. 1. 1.]
 [1. 1. 1.]] 

[[1 1 1]
 [1 1 1]] 

6 



Data type:

In [34]:
arr1 = np.array([111, 2.3,  True, False, False])
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [35]:
arr1.dtype

dtype('float64')

In [36]:
arr2 = np.array([111, 2.3, 'python', 'abc'])
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [37]:
arr2.dtype

dtype('<U32')

In [38]:
arr3 = np.array([111, True, 'abc'])
arr3

array(['111', 'True', 'abc'], dtype='<U21')

#### 1.3. Indexing and slicing NumPy arrays:

In [39]:
a = np.array([1, 2, 3, 4, 5])
a[2]

np.int64(3)

In [40]:
a[-1]

np.int64(5)

In [41]:
a[:]

array([1, 2, 3, 4, 5])

In [42]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a[1]

array([4, 5, 6])

In [44]:
a[-1]

array([7, 8, 9])

In [45]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
a[2][1]

np.int64(8)

In [47]:
a[2,1]

np.int64(8)

In [48]:
print(a, "\n")
print(a[0,2], "\n")
print(a[[0,2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

3 

[[1 2 3]
 [7 8 9]]


In [49]:
b = np.array([[1, 2, 3, 3], [4, 5, 6, 6], [7, 8, 9, 9], [10, 20, 30, 30], [40, 50, 60, 60]])
print(b, "\n")
print(b[[0,3]])
print(b[0,3])

[[ 1  2  3  3]
 [ 4  5  6  6]
 [ 7  8  9  9]
 [10 20 30 30]
 [40 50 60 60]] 

[[ 1  2  3  3]
 [10 20 30 30]]
3


In [50]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

Fancy indexing:

In [51]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 )
print(arr, "\n")
print(arrMask, "\n")
print(arr[arrMask], "\n")
print(type(arr[arrMask]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 

[ True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True False False False False  True False False False False  True
 False False False False  True False False False False  True False False
 False False  True False False False False  True False False False False
  True False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True False False False False  True False False False False  True
 False False False False] 

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95] 

<class 'numpy.nd

In [52]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

#### 1.4. NumPy attributes and reshaping:

In [53]:
a.size

9

In [54]:
a.shape

(3, 3)

In [55]:
a.ndim

2

In [56]:
len(a)

3

Change the shape with reshape() method:

In [57]:
a = np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
# reshape() just produced a 'view'.
# So, there is no permanent change to 'a'.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [61]:
a = a.reshape((2,2))
a

array([[2, 5],
       [1, 3]])

Careful that the reshape() method does not create a new object!

In [62]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999

In [63]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [64]:
# Make a copy in order to create a new object.
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

#### 1.5. Modifying NumPy arrays:

Appending elements, rows and columns to arrays:

In [65]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [66]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
print(a, "\n")
print(b)

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]
 [9 9]]


In [67]:
c = np.append(a, [[9], [9]] , axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

In [68]:
g = np.array([[9], [9]])
print(g)
print(g.shape, "\n")

d = np.array([[1, 2]])
print(d)
print(d.shape, "\n")

e = np.array([1, 2])
print(e)
print(e.shape, "\n")
print(e.ndim)

[[9]
 [9]]
(2, 1) 

[[1 2]]
(1, 2) 

[1 2]
(2,) 

1


In [69]:
d = np.array([[[[[[1, 2]]]]]])
print(d)
print(d.shape, "\n")


[[[[[[1 2]]]]]]
(1, 1, 1, 1, 1, 2) 



Deleting array elements, rows and columns:

In [70]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a, "\n")
print(np.delete(a, 0), "\n")
print(a)

[[1 2 3]
 [4 5 6]] 

[2 3 4 5 6] 

[[1 2 3]
 [4 5 6]]


In [71]:
print(np.delete(a, (0, 2, 4)))

[2 4 6]


In [72]:
print(np.delete(a, 0, axis = 0))

[[4 5 6]]


In [73]:
print(np.delete(a, 1, axis = 1))

[[1 3]
 [4 6]]
