<a href="https://colab.research.google.com/github/Akash-12-web/Samsung-Inovation-AIML/blob/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_03_Coding_Exercises/ex_0202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Coding Exercise #0202

### 1. NumPy array operations:

#### 1.1. '+' and '*' operators for Python lists:

In [1]:
import numpy as np

In [3]:
a = [1, 2, 3]

In [4]:
a + a

[1, 2, 3, 1, 2, 3]

In [5]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
b = np.array([1, 2, 3])

In [7]:
b*3

array([3, 6, 9])

In [8]:
b + b

array([2, 4, 6])

In [9]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### 1.2. '+' and '*' operators for NumPy arrays:

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [11]:
a+b

array([5, 7, 9])

In [12]:
a-b

array([-3, -3, -3])

In [13]:
a*b

array([ 4, 10, 18])

In [14]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 1.3. Universal functions:

In [15]:
x = np.array([0, 1, 2, 3, 4, 5])

In [16]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [17]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [18]:
type(np.sqrt)

numpy.ufunc

In [19]:
type(np.exp)

numpy.ufunc

#### 1.4. NumPy functions:

In [20]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [21]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.median(a)

np.float64(5.0)

In [23]:
np.sum(a)

np.int64(5485)

In [24]:
np.round(np.var(a),2)

np.float64(8.19)

In [25]:
np.round(np.mean(a),2)

np.float64(5.48)

In [26]:
np.round(np.std(a),2)

np.float64(2.86)

In [27]:
np.max(a)

np.int64(10)

In [28]:
np.min(a)

np.int64(1)

#### 1.5. Statistical methods of NumPy arrays:

In [29]:
x=np.arange(1,11)

In [30]:
x.sum()

np.int64(55)

In [31]:
x.mean()

np.float64(5.5)

In [32]:
x.std()

np.float64(2.8722813232690143)

In [33]:
x.var()

np.float64(8.25)

In [34]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [35]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(y.mean(axis=0))

[4. 5. 6.]


In [37]:
print(y.mean(axis=1))

[2. 5. 8.]


In [38]:
z = np.random.randint(10,size=1000)

In [39]:
z.max()

np.int64(9)

In [40]:
z.min()

np.int64(0)

In [41]:
(z > 5).sum()

np.int64(392)

In [42]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
sorted(set(z))

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [44]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [45]:
a.argmax()

np.int64(4)

In [46]:
a.argmin()

np.int64(1)